# Basics of the comand 'print'
print('Hello'+' '+ 'World')
print('Whatsapp',  "Whatsapp", end='\t', sep='_')
print('hi', ' '*5, 'hi', sep='_')

print('#'*20)
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print('#'*20)
print("\n#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print('#'*20)
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
print("#", " "*18, "#", sep="")
